### ISSUE TITLE
Discord auth setup is confusing

### ISSUE THREAD

**Issue by clburlison** [versx/ChuckDeviceController#45]
**Describe the bug**
Build any commit of Chuck after #43 has been enabled. Discord auth is now forced and there is no easy way to allow users to submit the Discord settings. 

**To Reproduce**
1. Build latest commit with a clean database
2. Run Chuck `dotnet ChuckDeviceController.dll`
3. Load Chuck in browser http://localhost:5000
4. Page will not load since the required Metadata Discord keys will not exist

**Expected behavior**
Chuck should create the required database keys. Additionally if Discord Auth is not setup users should be able to access the site.
```sql
INSERT INTO `metadata` (`key`, `value`) VALUES
('DISCORD_CLIENT_ID', NULL),
('DISCORD_CLIENT_SECRET', NULL),
('DISCORD_ENABLED', 'False'),
('DISCORD_REDIRECT_URI', NULL),
('DISCORD_USER_IDS', NULL);
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version v0.12.0 and later

**Smartphone (please complete the following information):**

**Additional context**
I believe this function is where logic should be changed to allow non-authenticated requests?  https://github.com/versx/ChuckDeviceController/commit/1e27e612e196b083118204667a385ce310b71c25#diff-47743c7a548540a7f5ca5f042a2b2c79cb438b361a13fd06c5744a002acc6bdcR211-R217

```sh
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/clayton/src/ChuckDeviceController/bin
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.UInt64.Parse(String s)
         at ChuckDeviceController.Controllers.DiscordController.LoadSettings() in /Users/clayton/src/ChuckDeviceController/src/ChuckDeviceController/Controllers/DiscordController.cs:line 58
         at ChuckDeviceController.Controllers.DiscordController..ctor(DeviceControllerContext context, ILogger`1 logger) in /Users/clayton/src/ChuckDeviceController/src/ChuckDeviceController/Controllers/DiscordController.cs:line 47
         at lambda_method70(Closure , IServiceProvider , Object[] )
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 103
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by darthbutcher** [comment]
Seconded.

**Comment by darthbutcher** [comment]
After looking at DiscordController.cs, it doesn't appear to reference the config file at all, either.

**Comment by clburlison** [comment]
Oh you're right! Sleep helps me realize this is similar to that _old_ we've used product 

```sql
INSERT INTO `metadata` (`key`, `value`) VALUES
('DISCORD_CLIENT_ID', NULL),
('DISCORD_CLIENT_SECRET', NULL),
('DISCORD_ENABLED', 'false'),
('DISCORD_REDIRECT_URI', NULL),
('DISCORD_USER_IDS', NULL);
```

with that said it looks like this function isn't working properly? When the `discord_enabled` value is set to `false` the discord login routing is still attempting to go through on my end. 
https://github.com/versx/ChuckDeviceController/commit/1e27e612e196b083118204667a385ce310b71c25#diff-47743c7a548540a7f5ca5f042a2b2c79cb438b361a13fd06c5744a002acc6bdcR211-R217

**Comment by darthbutcher** [comment]
@clburlison After adding this to my metadata table(and adding proper config options in the value column), I keep looping on authentication.

**Comment by versx** [comment]
Should hopefully be fixed with: 
https://github.com/versx/ChuckDeviceController/commit/10dd2eed2666061f84af1ec65dd1aaa11d9e2768#diff-2f644a6f2281c5f837d817a58b76f7877a61630117f140b8de968ce45381b91cR23

**Comment by clburlison** [comment]
It's 90% fixed. The outstanding issue is https://github.com/versx/ChuckDeviceController/blob/524eaed36d8723dd270ca279a83be4d2d561d50a/src/ChuckDeviceController/Controllers/DashboardController.cs#L1812

If the `DISCORD_ENABLED` database key doesn't exist the bool.Parse will fail since it sees a null value.

As such all primary pages will load except for the http://localhost:5000/dashboard/settings route.

**Comment by versx** [comment]
> It's 90% fixed. The outstanding issue is
> 
> https://github.com/versx/ChuckDeviceController/blob/524eaed36d8723dd270ca279a83be4d2d561d50a/src/ChuckDeviceController/Controllers/DashboardController.cs#L1812
> 
> If the `DISCORD_ENABLED` database key doesn't exist the bool.Parse will fail since it sees a null value.
> 
> As such all primary pages will load except for the http://localhost:5000/dashboard/settings route.

Thanks I'll fix that and provide a default valid. What are your thoughts on just leaving Discord settings via the config and making the admin force a restart instead of dynamically loading after changing via the Settings page? Leaving them in the config definitely makes it easier/nicer to deal with, instead of creating some static class with static variables keeping track of the latest config values. Although I'm up for either.

**Comment by clburlison** [comment]
I'd go with the easier solution of baking it into the config file. Dynamic loading is kinda fluff.

**Comment by versx** [comment]
Makes it easier for my future plans. 😄

**Comment by clburlison** [comment]
If it's a requirement for later then all for it. Happy to help were & when I can.

**Comment by versx** [comment]
Should be fixed in https://github.com/versx/ChuckDeviceController/pull/47
